### ISSUE TITLE
Hard-coded username/password in do-init.sjs

### ISSUE THREAD

**Issue by hanshuebner** [fgeorges/expath-ml-console#18]
Do you have any plans or guidance for passing the database password to the `get(url)` function in `do-init.sjs`?  We would like to upgrade our console installations, but we will not be able to hard code the username and password in that function because they vary between systems.

**Comment by fgeorges** [comment]
Hi Hans.  Could you by any chance try the branch `feature/qbooks`?  It offers a form instead of having it hard-coded.

If you are not in a hurry, and can wait a couple of weeks, I recommend you wait for my next merge to `master` (that change will be part of it).

As a matter of fact, I thought I should probably remove that **hard requirement** to initialize the system (if not you are always redirected until it is done).  But rather disabling the feature depending on it until init is done, and have a "config" page to do it when/if necessary.

The one feature depending on initialization for now is the ML functions auto-completion in code editors.  Not really something that should block using the system.

I will try and have that change before the next merge, so you wouldn't need the credentials anymore, unless you want function names auto-completion.

**Comment by hanshuebner** [comment]
We can wait for a few weeks, thanks for fixing this!

**Comment by fgeorges** [comment]
Hi @hanshuebner.  I did not forget about you :-)  This must be in `master` now.  Can you give it a try?

So now, it is not necessary to initialise the console anymore.  But still you can do it (link on the homepage if it has not been initialised yet), especially to get ML function completion (both SJS and XQY) working when editing modules through the ML Console.

**Comment by hanshuebner** [comment]
Hi @fgeorges, I tried the current master and it works fine without setup, thanks for that!

**Comment by fgeorges** [comment]
Great, thanks for reporting this, and for waiting for the fix.

On a side note, you might be interested by a new featured I am adding, to save and execute queries in Markdown files (so you can share them amongst users, organise them in dirs and files, and save them in Git): https://github.com/fgeorges/expath-ml-console/blob/master/test/qbooks/intro.md.
