### ISSUE TITLE
Please add a roxy or ml-gradle deployment option

### ISSUE THREAD

**Issue by sashamitrovich** [fgeorges/expath-ml-console#8]
Would be nice to be able to deploy and get it to run easily.

**Comment by fgeorges** [comment]
Hi Saša!

The Console comes with [mlproj](http://mlproj.org/) descriptors.  For now it is only on branches `develop` and `project-environs`.

I recommend using `develop` instead of `master` anyway, I should merge it there.  The difference between `develop` and `project-environs` is some support for `mlproj` in the Console, to give it a web UI.

The [beginning of the README file](https://github.com/fgeorges/expath-ml-console/tree/develop#install) on these branches contains the few necessary details.  But in a few words:

    $ npm install mlproj -g                # install mlproj if not already
    $ mlproj -e dev setup
    $ mlproj -e dev deploy

Thanks for your suggestion though!
