### ISSUE TITLE
Saving a document in the document browser removes its collections

### ISSUE THREAD

**Issue by hanshuebner** [fgeorges/expath-ml-console#9]
When I save a document that has collections attached to it, the collections are lost afterwards.  Here's a screenshot from when I pressed "Save":

![image](https://user-images.githubusercontent.com/108751/37612187-ca9f4bcc-2ba4-11e8-8ac6-0a90f3746983.png)

When I dismiss the requester, the collections are still shown, but once I reload the page, they are gone:

![image](https://user-images.githubusercontent.com/108751/37612207-d9cd405e-2ba4-11e8-99a4-a8663c26a959.png)

**Comment by fgeorges** [comment]
Thank you, @hanshuebner !

Which branch are you on?  I take great care of replacing the content of the existing node if any, instead of using document-insert, precisely to keep everything (collections, metadata, permissions...)

Is it possible you use master?  This seems to be the case also by looking at the URL you have in your browser (they have been changed some time ago, to support any sort of "URI root", not only "/").

Can you make sure you use `project-environs`?  And yes, I should really merge to master...

If you used mlproj to install, you simply need to `git checkout project-environs` then `mlproj deploy`.

**Comment by hanshuebner** [comment]
I'm using master, as that is what the README told me to do.  Maybe you want to just rename `project-environs` to `master` to avoid this?  With the `project-environs` branch, the problem is indeed gone.  Thanks!
